apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache 
    spec:
      containers:
      - name: nodeserver
        image: dockerfile
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  selector:
    app: apache 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8979
    targetPort: 80
    nodePort: 31110
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: friday.om
spec:
  rules:
    - host: friday.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apache-service
                port:
                  number: 80
